name: rnapheno
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - gtfparse
  - pysam=0.16.0.1
  - regtools
  - rsem
  - scikit-learn
  - snakemake
  - star
  - subread
  - telescope
  - kallisto
  - txrevise
  - r-optparse
  - gffread
