# Raw RNA-Seq data
fastq_map: TURNAP/test/input/fastq_map.txt
fastq_dir: TURNAP/test/input/fastq
paired_end: True
read_length: 75

# Reference files
ref_genome: TURNAP/test/input/ref/Homo_sapiens.GRCh38.dna.primary_assembly.chr1_0-1Mb.fa
ref_anno: TURNAP/test/input/ref/Homo_sapiens.GRCh38.106.chr1_0-1Mb.gtf
retro_anno: TURNAP/test/input/ref/retro.hg38.v1.nochr.chr1_0-1Mb.gtf

# Project
project_dir: TURNAP/test/output
ref_dir: TURNAP/test/output/ref
threads: 4

# Phenotypes
phenotypes:
  expression:
    files:
    - expression.bed.gz
    - expression.bed.gz.tbi
  splicing:
    files:
    - splicing.bed.gz
    - splicing.bed.gz.tbi
    - splicing.phenotype_groups.txt
  stability:
    files:
    - stability.bed.gz
    - stability.bed.gz.tbi
  retroelements:
    files:
    - retroelements.bed.gz
    - retroelements.bed.gz.tbi
  latent:
    files:
    - latent.bed.gz
    - latent.bed.gz.tbi
    - latent.phenotype_groups.txt
