# Raw RNA-Seq data
fastq_map: data/geuvadis/fastq_map.txt
fastq_dir: data/geuvadis
paired_end: True
read_length: 75

# Reference files
ref_genome: data/human_ref/Homo_sapiens.GRCh38.dna.primary_assembly.fa
ref_anno: data/human_ref/Homo_sapiens.GRCh38.106.gtf
retro_anno: data/human_ref/retro.hg38.v1.nochr.gtf

# Project
project_dir: test
ref_dir: test/reference
threads: 4

# Phenotypes
phenotypes:
  expression:
    files:
    - expression.log2.bed
    - expression.tpm.bed
  splicing:
    files:
    - splicing.bed
  stability:
    files:
    - stability.bed
  retroelements:
    files:
    - retroelements.bed
  # ATS_APA:
  #   files:
  #   - ATS_APA.bed
  latent:
    files:
    - latent.bed
