# Raw RNA-Seq data
fastq_map: data/geuvadis/fastq_map.txt
fastq_dir: data/geuvadis
paired_end: True
read_length: 75

# Reference files
ref_genome: data/human_ref/Homo_sapiens.GRCh38.dna.primary_assembly.fa
ref_anno: data/human_ref/Homo_sapiens.GRCh38.106.gtf
retro_anno: data/human_ref/retro.hg38.v1.nochr.gtf

# Project
project_dir: test
ref_dir: test/reference
threads: 4

# Phenotypes
phenotypes:
  expression:
    files:
    - expression.bed.gz
    - expression.bed.gz.tbi
  splicing:
    files:
    - splicing.bed.gz
    - splicing.bed.gz.tbi
    - splicing.phenotype_groups.txt
  stability:
    files:
    - stability.bed.gz
    - stability.bed.gz.tbi
  retroelements:
    files:
    - retroelements.bed.gz
    - retroelements.bed.gz.tbi
  latent:
    files:
    - latent.bed.gz
    - latent.bed.gz.tbi
    - latent.phenotype_groups.txt
