# Raw RNA-Seq data
fastq_dir: input/fastq
fastq_map: input/fastq_map.txt
bam_dir: input/bam
bam_map: input/bam_map.txt
paired_end: True
read_length: 75

# Reference files
ref_genome: input/ref/Homo_sapiens.GRCh38.dna.primary_assembly.chr1_0-1Mb.fa
ref_anno: input/ref/Homo_sapiens.GRCh38.106.chr1_0-1Mb.gtf
ref_cdna: 'input/ref/Homo_sapiens.GRCh38.cdna.all.fa.gz'
retro_anno: input/ref/retro.hg38.v1.nochr.chr1_0-1Mb.gtf

# Files and info for downstream analysis
# TODO: Get chromosome list automatically from genotypes or BED file.
chroms: [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22]
samples_file: input/samples.txt
geno_prefix: path/to/plink/bed/bim/fam/genotypes
covar_file: path/to/covar/file.txt

# Other parameters:
genome_size: 1000000

# Phenotypes
phenotypes:
  ATS_APA:
    files:
    - ATS_APA.grp_1.upstream.bed.gz
    - ATS_APA.grp_1.upstream.bed.gz.tbi
    - ATS_APA.grp_1.upstream.phenotype_groups.txt
    - ATS_APA.grp_1.contained.bed.gz
    - ATS_APA.grp_1.contained.bed.gz.tbi
    - ATS_APA.grp_1.contained.phenotype_groups.txt
    - ATS_APA.grp_1.downstream.bed.gz
    - ATS_APA.grp_1.downstream.bed.gz.tbi
    - ATS_APA.grp_1.downstream.phenotype_groups.txt
    - ATS_APA.grp_2.upstream.bed.gz
    - ATS_APA.grp_2.upstream.bed.gz.tbi
    - ATS_APA.grp_2.upstream.phenotype_groups.txt
    - ATS_APA.grp_2.contained.bed.gz
    - ATS_APA.grp_2.contained.bed.gz.tbi
    - ATS_APA.grp_2.contained.phenotype_groups.txt
    - ATS_APA.grp_2.downstream.bed.gz
    - ATS_APA.grp_2.downstream.bed.gz.tbi
    - ATS_APA.grp_2.downstream.phenotype_groups.txt
  expression:
    files:
    - expression.genes.bed.gz
    - expression.genes.bed.gz.tbi
    - expression.isoforms.bed.gz
    - expression.isoforms.bed.gz.tbi
    - expression.isoforms.phenotype_groups.txt
  latent:
    files:
    - latent.bed.gz
    - latent.bed.gz.tbi
    - latent.phenotype_groups.txt
  retroelements:
    files:
    - retroelements.bed.gz
    - retroelements.bed.gz.tbi
  splicing:
    files:
    - splicing.bed.gz
    - splicing.bed.gz.tbi
    - splicing.phenotype_groups.txt
  stability:
    files:
    - stability.bed.gz
    - stability.bed.gz.tbi
