name: pheast
# channels:
#   - conda-forge
#   - bioconda
#   - defaults
dependencies:
  - bioconductor-impute
  - bioconductor-qvalue
  - bioconductor-variantannotation
  - gcta
  - pip
  - plink2=2
  - python=3.9 # tensorqtl imports deprecated collections.Iterable
  - rpy2
  - snakemake
  - pip:
    - tensorqtl
