# Point to the Pantry output directory containing BED files:
phenotype_dir: ../Project/output

# Give the path prefix to genotypes in plink1 (bed/bim/fam) format:
geno_prefix: input/GEUVADIS.445_samples.GRCh38.chr1_0-1Mb

## Samples to include:
samples_file: ../Project/input/samples.txt

## Phenotypes
# List the phenotype categories to extract, with list of expected output files for each.
# A snakefile will be loaded for each category, steps/{phenotype}.smk
phenotypes:
  alt_polyA:
    grouped: true
  alt_TSS:
    grouped: true
  expression:
    grouped: false
  isoforms:
    grouped: true
  latent:
    grouped: true
  # retroelements:
  #   grouped: false
  splicing:
    grouped: true
  # stability:
  #   grouped: false
